### ISSUE TITLE
Windows wheels ABI tag is (probably) too restrictive

### ISSUE THREAD

**Issue by andreasxp** [asottile/dockerfile#164]
Hi again and thank you very much for providing windows wheels.

There's a small issue - the wheel is tagged as `dockerfile-3.3.0-cp38-cp38-win_amd64.whl`, the second `cp38` is an ABI tag that restricts the wheel to python 3.8 only, so pip on other versions refuses to install this wheel and attempts to build from source anyway. You can reproduce with:
```
PS> pip --version
pip 23.2.1 from [...] (python 3.11)

PS> pip install --only-binary=:all: dockerfile
ERROR: Could not find a version that satisfies the requirement dockerfile (from versions: none)
ERROR: No matching distribution found for dockerfile
```

However, when I manually downloaded the wheel and renamed it to `dockerfile-3.3.0-cp38-abi3-win_amd64.whl`, it installed and worked perfectly well, so it's likely just mislabeled.

Could you please take a look?

**Comment by asottile** [comment]
looks like the setup.py was not updated from the era when windows did not have abi3 support: https://github.com/asottile/dockerfile/blob/ee7f769ac666ab4b176c88a3c1989336ce551dd4/setup.py#L9
