### ISSUE TITLE
docker/docker/builder/dockerfile/parser dependency moved

### ISSUE THREAD

**Issue by ahmetb** [asottile/dockerfile#31]
FYI the https://godoc.org/github.com/docker/docker/builder/dockerfile/parser package no longer exists.

https://godoc.org/github.com/asottile/dockerfile?import-graph&hide=1

**Comment by asottile** [comment]
yeah it probably moved again -- this is why I used `vendor` :) -- want to supply a PR bumping the submodule and using the new location?
