### ISSUE TITLE
Support comments, directives, and HEALTHCHECK options

### ISSUE THREAD

**Issue by spearsem** [asottile/dockerfile#7]
`dockerfile` doesn't return the result of parsed comment lines from a source Dockerfile. While it might be inconvenient but at least tolerable to work around parsing pure comment lines, there is also [the `escape` directive](https://docs.docker.com/engine/reference/builder/#escape) that is specified via a special comment line, and has a semantic effect on the rest of the file. Ability to parse `escape` directives is necessary.

I also noticed that a parsed `HEALTHCHECK` command does not put the option argument into the `value` part of the returned command, only the `CMD` part. E.g. this line of a Dockerfile

```
HEALTHCHECK \
  --interval=3s \
  --timeout=30s \
  --start-period=10s \
  --retries=3 \
  CMD echo 'hello'
```

parses into this `Command`:

```
Command(cmd='healthcheck', sub_cmd=None, json=False, original="HEALTHCHECK --interval=3s --timeout=30s --start-period=10s --retries=3   CMD echo 'hello'", start_line=9, value=('CMD', "echo 'hello'"))
```

Similarly, the `--from` option of the `COPY` command is not captured, exactly in the same manner as the`HEALTHCHECK` options (this is particularly important for multi-stage builds).

As a side note, I have just begun some work on a separate project that will make use of your `dockerfile` Python wrapper. Thanks very much for making this ... and let me know how I can contribute if you'd like some help with actively maintaining this project.

**Comment by asottile** [comment]
Hello @spearsem!  First off thanks for the issue!

As for comments, yeah I'd really like for them to round trip but unfortunately the underlying parser I'm wrapping doesn't support that.

As for `HEALTHCHECK` and `COPY`, it's likely they weren't in existence when I wrote my wrapper -- it's probably that updating the submodule and adding a little smarts around those would make this work as expected :)

As for extending for options, you'd probably [want to look here](https://github.com/asottile/dockerfile/blob/master/parse.go), and then hook it up with the python bits [here](https://github.com/asottile/dockerfile/blob/master/pylib/main.go)

I think the escape directive *is* parsed by docker's file parser so it should be possible to coerce out.

Also -- glad you starred, I accidentally unwatched my own repository (oops) and didn't even notice this issue!

**Comment by asottile** [comment]
Oh, another idea to preserve the whitespace and comments: since we get line numbers you can slice in the gaps (using a similar approach as I use in https://github.com/asottile/tokenize-rt) on my phone or I'd give a code sample 😆
