### ISSUE TITLE
Finer-grained support for `ARG name=value`

### ISSUE THREAD

**Issue by woodruffw** [asottile/dockerfile#72]
First of all, thanks a ton for writing these Python bindings -- they've been a pleasure to use 🙂 

I've been using `dockerfile` on a project of mine, and I noticed that lines of the form `ARG name=value` are represented as though `name=value` is a single AST `value`, rather than an associative pair. For example:

```python
>>> import dockerfile
>>> dockerfile.parse_string("ARG FOO=/foo")[0]
Command(cmd='arg', sub_cmd=None, json=False, original='ARG FOO=/foo', start_line=1, end_line=1, flags=(), value=('FOO=/foo',))
```

I realize this would be a breaking change and would thus warrant a new major version, but it'd be great if this was represented with a two-tuple of `(name, value)` instead. I'm not great with Go, but I did a cursory scan of the Dockerfile parser and I _think_ this information is saved somewhere in the AST nodes that this wrapper is encapsulating:

```go
// parse environment like statements. Note that this does *not* handle
// variable interpolation, which will be handled in the evaluator.
func parseNameVal(rest string, key string, d *directives) (*Node, error) {
	// This is kind of tricky because we need to support the old
	// variant:   KEY name value
	// as well as the new one:    KEY name=value ...
	// The trigger to know which one is being used will be whether we hit
	// a space or = first.  space ==> old, "=" ==> new


	words := parseWords(rest, d)
	if len(words) == 0 {
		return nil, nil
	}


	// Old format (KEY name value)
	if !strings.Contains(words[0], "=") {
		parts := reWhitespace.Split(rest, 2)
		if len(parts) < 2 {
			return nil, fmt.Errorf(key + " must have two arguments")
		}
		return newKeyValueNode(parts[0], parts[1]), nil
	}


	var rootNode *Node
	var prevNode *Node
	for _, word := range words {
		if !strings.Contains(word, "=") {
			return nil, fmt.Errorf("Syntax error - can't find = in %q. Must be of the form: name=value", word)
		}


		parts := strings.SplitN(word, "=", 2)
		node := newKeyValueNode(parts[0], parts[1])
		rootNode, prevNode = appendKeyValueNode(node, rootNode, prevNode)
	}


	return rootNode, nil
}
```

(Permalink: https://github.com/moby/buildkit/blob/1c037fd52f3481aded331ee74bff7cb1b4d99be6/frontend/dockerfile/parser/line_parsers.go#L139-L175)

**Comment by asottile** [comment]
that function isn't public (and I don't really want to break the api) so there isn't anything we can really do here -- feel free to take the logic though and make your own helper function  👍 -- shouldn't be too difficult to parse the `ARG`

**Comment by woodruffw** [comment]
Sorry, I didn't realize that `parse_string` isn't public -- is that documented anywhere? The README lists it as one of the three APIs for this library.

In any case, thanks for the quick response! Doing it with my own helper is fine; just wanted to see if there was interest 🙂

**Comment by asottile** [comment]
no I mean the go code you linked is not public
